# deployment-odoo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: souhaila999/app-odoo:15.0
        ports:
        - containerPort: 8069
        envFrom:
        - configMapRef:
            name: odoo-config
        args: ["-i", "base", "--load=base"]

---
# service-odoo.yaml
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo-namespace
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  type: LoadBalancer

